// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Fe0AgZCmaJj-njNTlqmqhqidk4zGTf4',
    appId: '1:363133217072:web:bdca3a20f96ad0334500f5',
    messagingSenderId: '363133217072',
    projectId: 'flutterfirebasechat-6e27a',
    authDomain: 'flutterfirebasechat-6e27a.firebaseapp.com',
    storageBucket: 'flutterfirebasechat-6e27a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJpRSmjDRKgiEeC_JRaKaY9oZ6HpYFrHw',
    appId: '1:363133217072:android:fab9088917de4cf74500f5',
    messagingSenderId: '363133217072',
    projectId: 'flutterfirebasechat-6e27a',
    storageBucket: 'flutterfirebasechat-6e27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEyJVqICHHrurkccU85D31So3qsYJn-28',
    appId: '1:363133217072:ios:e8f383dbe16df7614500f5',
    messagingSenderId: '363133217072',
    projectId: 'flutterfirebasechat-6e27a',
    storageBucket: 'flutterfirebasechat-6e27a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseChatingApp',
  );
}
